apiVersion: v1
kind: Service
metadata:
  name: restaurant-menu-service
spec:
  selector:
    app: restaurant-menu # same as deployment name
  ports:
    - protocol: "TCP"
      port: 9091
      targetPort: 9091
  type: NodePort
